spring:
  application:
    name: consumer-app
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: localhost:9092
    group-id: consumer-group
    topic:
      name: test-topic
server:
  port: 8081